### ISSUE TITLE
Changing service port requires a change in Omero configmap

### ISSUE THREAD

**Issue by ClementGautier** [manics/kubernetes-omero#27]
Hi,

I struggled a little bit to change the default port, setting service.port isn't enough as it change the container port but omero by default will still listen to 4064, you need to put this in the values:
``` yaml
service:
  port: 1234
config:
  set:
    "omero.ports.ssl": 1234
```
Maybe we could automate that in the configmap so future users don't waste time?
I can provide the PR if you think it's relevant
